version: '3.9'
services:
  backend:
    container_name: main_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python app.py'
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    environment:
      SQLALCHEMY_DATABASE_URI: 'mysql://user:user@main_db/main'
    depends_on:
      db:
        condition: service_healthy

  queue:
    container_name: main_queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: main_db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33067:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10